version: '3.8'
services:

  lesson-postgres:
    image: postgres:12.4-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
    - './postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=yakov
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=test


  lesson-php-fpm:
    restart: on-failure
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - './symfony:/var/www/lesson-symfony'
    links:
      - lesson-postgres
      - lesson-elasticsearch


  lesson-nginx:
    restart: on-failure
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - './symfony:/var/www/lesson-symfony'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - lesson-php-fpm
    ports:
      - 80:80

  lesson-elasticsearch:
      image: sebp/elk:792
      environment:
        - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      ports:
        - 9200:9200
#      volumes:
#        - './symfony:/usr/share/elasticsearch/data'