version: '3.8'
services:

  lesson-postgres:
    image: postgres:12.4-alpine
    container_name: lesson-postgres
#    restart: on-failure
    ports:
      - 5432:5432
    volumes:
    - './postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=yakov
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=test


  lesson-php-fpm:
    restart: on-failure
    container_name: lesson-php-fpm
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - './symfony:/var/www/lesson-symfony'
    links:
      - lesson-postgres

  lesson-nginx:
    restart: on-failure
    container_name: lesson-nginx
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - './symfony:/var/www/lesson-symfony'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - lesson-php-fpm
    ports:
      - 80:80





#  lesson-mysql:
#    image: mysql:latest
#    container_name: lesson-mysql
##    command: --default-authentication-plugin=mysql_native_password
#    environment:
#     MYSQL_ROOT_PASSWORD: 1
#     MYSQL_USER: yakov
#     MYSQL_PASSWORD: 123
#     MYSQL_DATABASE: lessons
#    volumes:
#      - ./mysql:/var/lib/mysql
#    ports:
#    - 3306:3306
