# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: 'http://lesson-elasticsearch:9200' }
    indexes:
        product:
            persistence:
                # the driver can be orm, mongodb or phpcr
                driver: orm
                model: App\Entity\Product
                provider: ~
                listener: ~
                finder: ~
            properties:
                name: ~
                description: ~
